class InsertDataIntoProvince < ActiveRecord::Migration[5.1]
  def change
    execute("insert into provinces(id, name, created_at, updated_at) values(1,  'Amnat Charoen', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(2,  'Ang Thong', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(3,  'Ayutthaya', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(4,  'Bangkok', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(5,  'Bueng Kan', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(6,  'Buriram', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(7,  'Chachoengsao', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(8,  'Chainat', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(9,  'Chaiyaphum', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(10,  'Chanthaburi', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(11,  'Chiang Mai', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(12,  'Chiang Rai', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(13,  'Chonburi', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(14,  'Chumphon', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(15,  'Kalasin', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(16,  'Kamphaeng Phet', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(17,  'Kanchanaburi', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(18,  'Khon Kaen', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(19,  'Krabi', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(20,  'Lampang', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(21,  'Lamphun', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(22,  'Loei', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(23,  'Lopburi', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(24,  'Mae Hong Son', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(25,  'Maha Sarakham', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(26,  'Mukdahan', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(27,  'Nakhon Nayok', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(28,  'Nakhon Pathom', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(29,  'Nakhon Phanom', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(30,  'Nakhon Ratchasima', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(31,  'Nakhon Sawan', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(32,  'Nakhon Si Thammarat', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(33,  'Nan', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(34,  'Narathiwat', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(35,  'Nong Bua Lamphu', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(36,  'Nong Khai', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(37,  'Nonthaburi', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(38,  'Pathum Thani', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(39,  'Pattani', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(40,  'Phang Nga', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(41,  'Phatthalung', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(42,  'Phayao', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(43,  'Phetchabun', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(44,  'Phetchaburi', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(45,  'Phichit', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(46,  'Phitsanulok', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(47,  'Phrae', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(48,  'Phuket', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(49,  'Prachin Buri', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(50,  'Prachuap Khiri Khan', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(51,  'Ranong', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(52,  'Ratchaburi', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(53,  'Rayong', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(54,  'Roi Et', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(55,  'Sa Kaeo', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(56,  'Sakon Nakhon', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(57,  'Samut Prakan', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(58,  'Samut Sakhon', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(59,  'Samut Songkhram', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(60,  'Saraburi', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(61,  'Satun', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(62,  'Sing Buri', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(63,  'Sisaket', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(64,  'Songkhla', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(65,  'Sukhothai', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(66,  'Suphan Buri', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(67,  'Surat Thani', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(68,  'Surin', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(69,  'Tak', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(70,  'Trang', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(71,  'Trat', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(72,  'Ubon Ratchathani', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(73,  'Udon Thani', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(74,  'Uthai Thani', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(75,  'Uttaradit', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(76,  'Yala', current_timestamp, current_timestamp);")
    execute("insert into provinces(id, name, created_at, updated_at) values(77,  'Yasothon', current_timestamp, current_timestamp);")


  end
end
